FROM python:3

MAINTAINER "philipp-froehlich@hotmail.com"

WORKDIR /root

COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 5000

COPY classes classes

COPY server.py .

CMD ["python", "-u", "server.py"]